### ISSUE TITLE
Sidebar: Event list component

### ISSUE THREAD

**Issue by ShahmeerShahid** [DSC-UTMap/utmap-website#37]
**Acceptance Criteria**:

- Has title "Upcoming Events"
- Shows title, date, description (first 10 words), location
- When clicked expands to show full description (https://material-ui.com/components/accordion/)
![image](https://user-images.githubusercontent.com/37679657/106339389-72f76680-6264-11eb-9cfb-d35a40e1b207.png)

**Comment by crawsoir** [comment]
Will implement assuming this drop-down is not part of the design, based on meeting comments
![image](https://user-images.githubusercontent.com/25747480/107001670-08f52a80-6758-11eb-8f67-f232e237c3cc.png)
